### ISSUE TITLE
AttributeError: type object 'HATTokenizer' has no attribute 'register_for_auto_class'

### ISSUE THREAD

**Issue by tahirahmad2030** [coastalcph/hierarchical-transformers#3]
I am facing an issue while loading the model.

Code:
```
from transformers import AutoTokenizer, AutoModelForSequenceClassification
tokenizer = AutoTokenizer.from_pretrained("kiddothe2b/hierarchical-transformer-base-4096", trust_remote_code=True)
doc_classifier = AutoModelForSequenceClassification.from_pretrained("kiddothe2b/hierarchical-transformer-base-4096", trust_remote_code=True)
```

Error:
```
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "script.py", line 2, in <module>
    tokenizer = AutoTokenizer.from_pretrained("kiddothe2b/hierarchical-transformer-base-4096", trust_remote_code=True)
  File "/Users/espm1393/anaconda3/envs/percolator_3.8/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 645, in from_pretrained
    tokenizer_class.register_for_auto_class()
AttributeError: type object 'HATTokenizer' has no attribute 'register_for_auto_class'
```

**Comment by tahirahmad2030** [comment]
```
torch version: 1.12.1
transformers version: 4.26.0
tokenizers version: 0.11.6
```

**Comment by kryptec** [comment]
Same issue

```
pytorch: 1.13.1
transformers: 4.26.1 
datasets: 2.10.1
tokenizers: 0.13.2 
scikit-learn: 1.2.2
tqdm: 4.65.0
nltk: 3.8.1
```

**Comment by iliaschalkidis** [comment]
Hello everyone,

The model can be loaded with:

```
torch>=1.11.0
transformers=4.20.0
tokenizers=0.11.6
```

Can you please check the latest version of `transformers`, and `tokenizers` that doesn't lead to a loading error and let me know? 

Thanks!

**Comment by kryptec** [comment]
It looks like the issue is with `transformers`  it works in 4.25.1 and breaks in 4.26.0

**Comment by iliaschalkidis** [comment]
Cool, it was a very easy hot fix. I just have to copy paste this new function in the `tokenization_hat.py` file:

```python
    @classmethod
    def register_for_auto_class(cls, auto_class="AutoModel"):
        """
        Register this class with a given auto class. This should only be used for custom models as the ones in the
        library are already mapped with an auto class.
        <Tip warning={true}>
        This API is experimental and may have some slight breaking changes in the next releases.
        </Tip>
        Args:
            auto_class (`str` or `type`, *optional*, defaults to `"TFAutoModel"`):
                The auto class to register this new model with.
        """
        if not isinstance(auto_class, str):
            auto_class = auto_class.__name__

        import transformers.models.auto as auto_module

        if not hasattr(auto_module, auto_class):
            raise ValueError(f"{auto_class} is not a valid auto class.")

        cls._auto_class = auto_class
```

Now, it works for all versions up-to-date! I just tested with the latest `transformers-4.27.1`, enjoy!

**Comment by kryptec** [comment]
Thanks, working so far for me now!
